version: '3.9'

services:
  web:
    build: .
    container_name: p2c_web
    command: ["/entrypoint.sh"]
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1
      - SECRET_KEY=django-insecure-change-this-key-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    build: .
    container_name: p2c_celery
    entrypoint: ["/app/celery-entrypoint.sh"]
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1
      - SECRET_KEY=django-insecure-change-this-key-in-production
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: p2c_redis
    ports:
      - "6379:6379"
    restart: unless-stopped 