# Generated by Django 5.2.1 on 2025-06-25 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('user_prompt', models.TextField(verbose_name='Prompt del usuario')),
                ('user_level', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('user_interests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('generating_metadata', 'Generando Metadata'), ('metadata_ready', 'Metadata Lista'), ('generating_module_1', 'Generando Módulo 1'), ('ready', 'Listo para Consumir'), ('generating_remaining', 'Generando Módulos Restantes'), ('complete', 'Completo'), ('failed', 'Error en Generación')], default='generating_metadata', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('total_modules', models.PositiveIntegerField(default=4)),
                ('module_list', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('podcast_script', models.TextField(blank=True)),
                ('podcast_audio_url', models.URLField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('final_project_data', models.JSONField(blank=True, default=dict)),
                ('total_size_estimate', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='es', max_length=10)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('metadata_generation', 'Generación de Metadata'), ('module_generation', 'Generación de Módulo'), ('audio_generation', 'Generación de Audio'), ('video_search', 'Búsqueda de Videos'), ('completion', 'Finalización'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='courses.course')),
            ],
            options={
                'verbose_name': 'Log de Generación',
                'verbose_name_plural': 'Logs de Generación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_id', models.CharField(max_length=50)),
                ('module_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('objective', models.TextField(blank=True)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('practical_exercise', models.JSONField(blank=True, default=dict)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['module_order'],
                'unique_together': {('course', 'module_order')},
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.CharField(max_length=100)),
                ('chunk_order', models.PositiveIntegerField()),
                ('total_chunks', models.PositiveIntegerField(default=6)),
                ('content', models.TextField()),
                ('checksum', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='courses.module')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'ordering': ['chunk_order'],
                'unique_together': {('module', 'chunk_order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('embed_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.chunk')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_chunks', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('current_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.chunk')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso del Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
