# Generated by Django 5.2.1 on 2025-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
