# Generated by Django 5.2.1 on 2025-06-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_video_data_to_module'),
        ('courses', '0002_module_video_data'),
    ]

    operations = [
    ]
