# Generated by Django 5.2.1 on 2025-06-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_title_to_chunk'),
        ('courses', '0003_merge_20250625_1656'),
    ]

    operations = [
    ]
