# Generated by Django 5.2.1 on 2025-06-26 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20250625_1710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='courses_cou_course__119e53_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_cou_created_51cadc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user_level'], name='courses_cou_user_le_9da299_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'module_order'], name='courses_mod_course__9d929b_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['module_id'], name='courses_mod_module__a35ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course'], name='courses_use_user_id_c2730d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['course'], name='courses_use_course__a11bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['last_accessed'], name='courses_use_last_ac_97c80c_idx'),
        ),
    ]
