# Generated by Django 5.2.1 on 2025-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_add_database_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("generating_metadata", "Generando Metadata"),
                    ("generating_modules_metadata", "Generando Metadata de Módulos"),
                    ("metadata_ready", "Metadata Lista"),
                    ("generating_module_1", "Generando Módulo 1"),
                    ("ready", "Listo para Consumir"),
                    ("generating_remaining", "Generando Módulos Restantes"),
                    ("complete", "Completo"),
                    ("failed", "Error en Generación"),
                ],
                default="generating_metadata",
                max_length=30,
            ),
        ),
    ]
